### ISSUE TITLE
Link problems to their contest page

### ISSUE THREAD

**Issue by lukaszkucinski** [akoprow/cofoda#1]
Link problems to their contest page (e.g. link 669 D2 C to `https://codeforces.com/contest/1407/problem/C`, instead of `https://codeforces.com/problemset/problem/1407/C`).

**Comment by akoprow** [comment]
Closed in 91422006985949d6bfd1f2963b5596bb33eac5d3.

**Comment by akoprow** [comment]
Addressed in 9142200.
