### ISSUE TITLE
Issues with user data refresh.

### ISSUE THREAD

**Issue by akoprow** [akoprow/cofoda#36]
Reported by @lukaszkucinski, I wasn't able to reproduce.

![WhatsApp Image 2020-11-08 at 17 31 26](https://user-images.githubusercontent.com/243048/98594475-9dbcc900-22cc-11eb-9720-e4eb99d2a226.jpeg)

The most likely scenario is that:

1. Client thinks there's no user data and asks backend for a refresh.
1. Backend sends data to client.
1. Backend receives the query to refresh but sees that there's nothing to update.
1. Client waits for the backend reply that will never come, hence continuously displaying 'Loading'.

If that indeed is the case then the easiest solution would be to always update `meta.timesUpdated` on the backend, even if no real update takes place.  Alternatively to alleviate the issue we could delay the initial refresh on the client by a couple seconds, though that's not ideal as would delay the initial update for all new clients.

**Comment by akoprow** [comment]
Hopefully should be fixed in 36beea90b7077beb21d7b96bf5215d2c78eb8094.

**Comment by lukaszkucinski** [comment]
Thanks. Seems to be working. If anything changes I will let you know.
